import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseReleaseManifest, type ReleaseManifest } from "@koyori/core";

const siteRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(siteRoot, "../..");
const manifestPath = resolve(siteRoot, "public/releases/preview-mac-arm64.json");
const unreleasedPath = resolve(repositoryRoot, "docs/releases/unreleased.md");
const targetPath = resolve(siteRoot, "app/generated/release.ts");
const fallback = [
  "## 当前阶段",
  "",
  "Koyori 正在建立首版工程、公开文档与发布基线。",
  "",
  "- 尚无已发布安装包。",
  "- 尚无 GitHub Release 或稳定更新通道。",
  "- 已验证能力会随工程进展补充到公开文档。",
].join("\n");

async function readOptional(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") return null;
    throw error;
  }
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}

function stripFrontmatter(markdown: string): string {
  return markdown.replace(/^---\s*\n[\s\S]*?\n---\s*\n?/, "").trim();
}

const manifestText = await readOptional(manifestPath);
let releaseManifest: ReleaseManifest | null = null;
let releaseMarkdown = fallback;
let releaseSourceFound = false;
let releaseKind: "unreleased" | "published" = "unreleased";

if (manifestText !== null) {
  let parsed: unknown;
  try {
    parsed = JSON.parse(manifestText);
  } catch (error) {
    throw new Error(
      `Cannot parse ${manifestPath}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  releaseManifest = parseReleaseManifest(parsed);

  const releasePath = resolve(repositoryRoot, `docs/releases/v${releaseManifest.version}.md`);
  const releaseText = await readOptional(releasePath);
  if (releaseText === null) {
    throw new Error(`Published manifest requires its unique release notes file: ${releasePath}`);
  }
  releaseMarkdown = stripFrontmatter(releaseText);
  releaseSourceFound = true;
  releaseKind = "published";
} else {
  const unreleased = await readOptional(unreleasedPath);
  if (unreleased !== null) {
    releaseMarkdown = stripFrontmatter(unreleased);
    releaseSourceFound = true;
  }
}

await access(repositoryRoot);
await mkdir(dirname(targetPath), { recursive: true });
const moduleSource = [
  "// Generated by scripts/sync-release.ts. Do not edit by hand.",
  'import type { ReleaseManifest } from "@koyori/core";',
  `export const releaseSourceFound = ${releaseSourceFound};`,
  `export const releaseKind: "unreleased" | "published" = ${JSON.stringify(releaseKind)};`,
  `export const releaseManifest: ReleaseManifest | null = ${JSON.stringify(releaseManifest)};`,
  `export const releaseMarkdown = ${JSON.stringify(releaseMarkdown)};`,
  "",
].join("\n");
await writeFile(targetPath, moduleSource, "utf8");
